# Generated by Django 5.2.8 on 2025-11-19 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre de la amenidad', max_length=50)),
            ],
            options={
                'verbose_name': 'amenidad',
                'verbose_name_plural': 'amenidades',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del propietario', max_length=100)),
                ('contact', models.CharField(help_text='Ingrese un teléfono o contacto', max_length=50)),
                ('email', models.EmailField(help_text='Ingrese el correo del propietario', max_length=100)),
            ],
            options={
                'verbose_name': 'propietario',
                'verbose_name_plural': 'propietarios',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el tipo de propiedad (casa, apartamento, etc.)', max_length=50)),
            ],
            options={
                'verbose_name': 'tipo de propiedad',
                'verbose_name_plural': 'tipos de propiedades',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ingrese el título de la propiedad', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Ingrese la descripción de la propiedad')),
                ('address', models.CharField(help_text='Ingrese la dirección de la propiedad', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Ingrese el precio de la propiedad', max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RENTED', 'Alquilada'), ('SOLD', 'Vendida'), ('MAINTENANCE', 'En Mantenimiento'), ('ACTIVE', 'Activa')], default='AVAILABLE', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.owner', verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'propiedad',
                'verbose_name_plural': 'propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity', verbose_name='amenidad')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='propiedad')),
            ],
            options={
                'verbose_name': 'amenidad de propiedad',
                'verbose_name_plural': 'amenidades de propiedades',
                'unique_together': {('property', 'amenity')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(through='properties.PropertyAmenity', to='properties.amenity', verbose_name='amenidades'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertytype', verbose_name='tipo de propiedad'),
        ),
    ]
