# Generated by Django 4.2.23 on 2026-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_area_property_rooms_alter_property_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyamenity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={},
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
