# Generated by Django 4.2.23 on 2026-06-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_amenity_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RENTED', 'Alquilada'), ('SOLD', 'Vendida'), ('MAINTENANCE', 'En Mantenimiento')], default='AVAILABLE', max_length=20),
        ),
    ]
