# Generated by Django 4.2.23 on 2026-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'propietario', 'verbose_name_plural': 'propietarios'},
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
        migrations.AddField(
            model_name='owner',
            name='contact',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
