# Generated by Django 5.2.8 on 2025-11-19 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del cliente', max_length=100)),
                ('address', models.CharField(help_text='Ingrese la dirección del cliente', max_length=150)),
                ('phone', models.CharField(help_text='Ingrese el teléfono del cliente', max_length=15)),
                ('email', models.EmailField(help_text='Ingrese el correo electrónico del cliente', max_length=100)),
                ('password', models.CharField(help_text='Ingrese la contraseña del cliente', max_length=100)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='ClientEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Ingrese una calificación de 1 a 5', verbose_name='calificación')),
                ('comments', models.TextField(blank=True, help_text='Ingrese comentarios adicionales', verbose_name='comentarios')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de evaluación')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='clients.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'evaluación de cliente',
                'verbose_name_plural': 'evaluaciones de clientes',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Ingrese la fecha de la visita', verbose_name='fecha de visita')),
                ('observations', models.TextField(blank=True, help_text='Ingrese observaciones de la visita', verbose_name='observaciones')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clients.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitas',
            },
        ),
    ]
