# Generated by Django 4.2.23 on 2026-06-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clientevaluation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='clientevaluation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='clientevaluation',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientevaluation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientevaluation',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
