# Generated by Django 4.2.23 on 2026-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_clientevaluation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
