# Generated by Django 4.2.23 on 2026-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cedula',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
