# Generated by Django 5.2.8 on 2025-11-19 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Ingrese la fecha de inicio del contrato', verbose_name='fecha de inicio')),
                ('end_date', models.DateField(help_text='Ingrese la fecha de finalización del contrato', verbose_name='fecha de finalización')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Ingrese el monto total del contrato', max_digits=12, verbose_name='monto total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client', verbose_name='cliente')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='properties.property', verbose_name='propiedad')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del documento', max_length=100, verbose_name='nombre del documento')),
                ('file', models.FileField(upload_to='contract_documents/', verbose_name='archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de subida')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract', verbose_name='contrato')),
            ],
            options={
                'verbose_name': 'documento de contrato',
                'verbose_name_plural': 'documentos de contratos',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Ingrese el monto del pago', max_digits=10, verbose_name='monto')),
                ('date', models.DateField(help_text='Ingrese la fecha del pago', verbose_name='fecha')),
                ('method', models.CharField(help_text='Ingrese el método de pago (efectivo, transferencia, etc.)', max_length=50, verbose_name='método de pago')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='contrato')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
