# Generated by Django 4.2.23 on 2026-06-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('RENT', 'Alquiler'), ('SALE', 'Venta')], default='RENT', max_length=10, verbose_name='tipo de contrato'),
        ),
    ]
